### ISSUE TITLE
Treatment must be coded 0,1 - effectlite does not support string factors

### ISSUE THREAD

**Issue by felixthoemmes** [amayer2010/EffectLiteR#1]
It would be nice if effectlite could handle factors that are coded as strings (e.g., "M","F"). Currently it requires that the treatment factor be hard-coded 0,1. Maybe some default behavior that would transform a factor with strings to a numeric 0,1 variable would be helpful. By default the first category of the factor could be coded 0. Ideally, effectlite would retain the actual level labels and displays them instead of using "Adj.Mean0", "Adj.Mean1".

Thanks Axel for putting effectlite into R!

#example below
y <- rnorm(100,0,1)
tr <- factor(c(rep("c",50),rep("t",50)))
df1 <- data.frame(y=y,tr=tr)
effectLite(y="y",x="tr",data=df1) #fails

df1$trn <- as.numeric(df1$tr)

effectLite(y="y",x="trn",data=df1) #fails

df1$trn2 <- as.numeric(df1$tr)-1

effectLite(y="y",x="trn2",data=df1) #succeeds

**Comment by amayer2010** [comment]
Thanks for using EffectLiteR, Felix. I assume you are using the CRAN version (0.4-2). This version can handle all sorts of factors, but you need to specify the control group in your call to effectLite if it's not "0" (the default in the CRAN version). That is the following works for your example:

effectLite(y="y", x="tr", data=df1, control="c")

In November last year, I changed this setting for the control argument to make it more convenient for users (and to be consistent with the shiny interface). In the development version in Github it is now control="default". The new help entry of the control argument in effectLite is: Value of x that is used as control group. If "default", takes the first entry of as.factor(x).

So in fact, your code does already work with the Github development version.

**Comment by felixthoemmes** [comment]
Thanks for the explanation, Axel!
