### ISSUE TITLE
wrong index in calculation of average covariate effects

### ISSUE THREAD

**Issue by langenberg** [amayer2010/EffectLiteR#2]
Hi Axel!

Could it be that the last index of the `a`-coefficients in the calculation of the average effects of the covariates is wrong? For each of the effects it should be increased by `1`.

I attached some example code for reproducing the bug.

All the best!

What it is:
`AveEffZ1 := a000*relfreq00 + a010*relfreq01 + a100*relfreq10 + a110*relfreq11 + a200*relfreq20 + a210*relfreq21`

How it should be (imho):
`AveEffZ1 := a001*relfreq00 + a011*relfreq01 + a101*relfreq10 + a111*relfreq11 + a201*relfreq20 + a211*relfreq21`

```
library(EffectLiteR)

data("example01")

fit <- effectLite(
    y = "dv",
    x = "x",
    k = c("k1"),
    z = c("z1", "z2"),
    data = example01,
    method = "sem",
    control = "control",
    measurement = character(),
    missing = "listwise",
    se = "standard",
    fixed.cell = "default",
    fixed.z = "default",
    interactions = "all",
    homoscedasticity = "default",
    test.stat = "default",
    propscore = NULL,
    ids = ~ 0,
    weights = NULL,
    add = character()
)

cat(fit@syntax@model)
```

```
[...]
## Average Effects of Continuous Covariates
AveEffZ1 := a000*relfreq00 + a010*relfreq01 + a100*relfreq10 + a110*relfreq11 + a200*relfreq20 + a210*relfreq21
AveEffZ2 := a001*relfreq00 + a011*relfreq01 + a101*relfreq10 + a111*relfreq11 + a201*relfreq20 + a211*relfreq21
```

**Comment by amayer2010** [comment]
fixed
